[package]
name = "auth"
version.workspace = true
edition.workspace = true

[dependencies]
argon2 = "0.5"
uuid = { version = "1", features = ["v4"] }
thiserror = "1"
rand_core = { version = "0.6", features = ["getrandom"] }

models = { path = "../models" }