[package]
name = "services"
version.workspace = true
edition.workspace = true

[dependencies]
uuid = { version = "1", features = ["v4"] }
time = { version = "0.3", features = ["serde"] }
thiserror = "1"

models = { path = "../models" }
storage = { path = "../storage" }
auth = { path = "../auth" }